### PR TITLE
release fixes

### PR DESCRIPTION
**Pull request by ThomasHP-EECA**
* Reworked overview page
* Fixed issue of group and item having the same label (e.g. Electricity the group & Electricity the fuel)
* Fixed proportional values in Time Series tab
* Tidied About tab

### CODE REVIEW

**Review by Achieeca — COMMENTED** [review]
It's looking great! Just one small note: if we need the. navbar-brand-container in the future, we could introduce feature toggles, which allows us to switch features on and off, enabling quick testing of different navigation bar designs without making code changes.

**Comment by ThomasHP-EECA** [comment]
> It's looking great! Just one small note: if we need the. navbar-brand-container in the future, we could introduce feature toggles, which allows us to switch features on and off, enabling quick testing of different navigation bar designs without making code changes.

I'm not sure I follow what you mean by this, could you elaborate?

**Comment by Achieeca** [comment]
I meant the one in the css file. But looks like it's an additional styling for the page title. Keeping it commented out make sense for future reference.

**Review by Achieeca — APPROVED** [review]
All the fixes looking great!

**Pull request merged**
